apiVersion: v1
kind: ConfigMap
metadata:
  name: student-app-config
  namespace: devops
data:
  spring.datasource.url: jdbc:mysql://mysql-service:3306/studentdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  spring.jpa.hibernate.ddl-auto: update
  spring.jpa.show-sql: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: student-app-secret
  namespace: devops
type: Opaque
data:
  spring.datasource.username: c3R1ZGVudA==  # student
  spring.datasource.password: c3R1ZGVudDEyMw==  # student123